# Generated by Django 3.1.8 on 2021-04-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="ID",
            new_name="id",
        ),
    ]
