# Generated by Django 3.1.8 on 2021-04-09 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import yt_video_translate.video_translator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_url', models.TextField()),
                ('youtube_title', models.CharField(blank=True, max_length=255)),
                ('video_clip', models.FileField(null=True, upload_to=yt_video_translate.video_translator.models.user_directory_path, verbose_name='')),
                ('silent_video_clip', models.FileField(null=True, upload_to=yt_video_translate.video_translator.models.user_directory_path, verbose_name='')),
                ('audio_clip', models.FileField(null=True, upload_to=yt_video_translate.video_translator.models.user_directory_path, verbose_name='')),
                ('translated_audio_clip', models.FileField(null=True, upload_to=yt_video_translate.video_translator.models.user_directory_path, verbose_name='')),
                ('translated_video_clip', models.FileField(null=True, upload_to=yt_video_translate.video_translator.models.user_directory_path, verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
