# Generated by Django 3.1.8 on 2021-04-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_translated',
            field=models.BooleanField(default=False),
        ),
    ]
