# Generated by Django 3.1.8 on 2021-04-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_translator', '0002_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummy',
        ),
    ]
