# Generated by Django 3.1.8 on 2021-04-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_translator', '0002_video_is_translated'),
        ('video_translator', '0003_delete_dummy'),
    ]

    operations = [
    ]
