# Generated by Django 3.1.8 on 2021-04-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_translator', '0004_merge_20210421_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='audio_clip',
        ),
        migrations.RemoveField(
            model_name='video',
            name='silent_video_clip',
        ),
    ]
